#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

CENTOS=centos7 # https://github.com/openstack/diskimage-builder/blob/be8d9b6/diskimage_builder/elements/centos7/environment.d/10-centos7-distro-name.bash#L1
UBUNTU=ubuntu # https://github.com/openstack/diskimage-builder/blob/be8d9b6/diskimage_builder/elements/ubuntu/environment.d/10-ubuntu-distro-name.bash#L1
TRUSTY=trusty
XENIAL=xenial # https://github.com/openstack/diskimage-builder/blob/be8d9b6/diskimage_builder/elements/ubuntu/environment.d/10-ubuntu-distro-name.bash#L2
BIONIC=bionic

if [ $DISTRO_NAME == $CENTOS ]; then
    yum install -y $(cat ${SCRIPTDIR}/yum-packages)

elif [ $DISTRO_NAME == $UBUNTU ]; then
    apt install -y $(cat ${SCRIPTDIR}/apt-metric-packages)
    apt install -y $(cat ${SCRIPTDIR}/apt-metric-packages-${DIB_RELEASE})
else
    echo "Unknown distribution name: '$DISTRO_NAME', only '$CENTOS' and '$UBUNTU' recognized"
    exit 1
fi

# collectd uses the default python version for ubuntu releases
# https://serverfault.com/questions/642893/using-collectd-with-python-3
# requests is required when running ceilometer plugin using python2
wget https://bootstrap.pypa.io/get-pip.py
python2 get-pip.py
pip2 install requests
# libvirt is required when running ceilometer plugin using python3
pip3 install libvirt-python

pip3 install gnocchiclient
