#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -x
set -o pipefail

NVIDIA_TMP_FOLDER=/root/tmp
export TMPDIR=$NVIDIA_TMP_FOLDER

#############################################################
# Installation (runfile)
#############################################################

# Install kernel headers and wget
sudo apt-get -qq install -y build-essential linux-headers-$(uname -r) wget

# Get the NVIDIA CUDA Toolkit for Ubuntu 16
wget -nv https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda_9.2.148_396.37_linux
mv cuda_9.2.148_396.37_linux cuda_9.2.148_396.37_linux.run
wget -nv https://developer.nvidia.com/compute/cuda/9.2/Prod2/patches/1/cuda_9.2.148.1_linux
mv cuda_9.2.148.1_linux cuda_9.2.148.1_linux.run

# Install the NVIDIA CUDA Toolkit for Ubuntu 16
sudo sh cuda_9.2.148_396.37_linux.run --samples --toolkit --driver --silent --verbose --tmpdir $NVIDIA_TMP_FOLDER

# Install patches
sudo sh cuda_9.2.148.1_linux.run --silent --accept-eula

exit 0
