#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -x
set -o pipefail

NVIDIA_TMP_FOLDER=/root/tmp
export TMPDIR=$NVIDIA_TMP_FOLDER

#############################################################
# Installation (runfile)
#############################################################

# compare chroot kernel with running kernel
CHROOT_KERNEL=$(basename $(ls -td -- /lib/modules/*/ | head -n 1))
RUNNING_KERNEL=$(uname -r)
if [ "$CHROOT_KERNEL" != "$RUNNING_KERNEL" ]; then
	echo "Unmatched kernel!"
	exit 1	
fi

# Install kernel headers and wget
sudo apt-get -qq install -y build-essential linux-headers-$(uname -r) wget

# Get the NVIDIA CUDA Toolkit for Ubuntu 16
wget -nv https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.168_418.67_linux.run

# Install the NVIDIA CUDA Toolkit for Ubuntu 16
sudo sh cuda_10.1.168_418.67_linux.run --samples --toolkit --driver --silent --tmpdir $NVIDIA_TMP_FOLDER

exit 0
