#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

mkdir -p /opt/chameleon

cd /opt/chameleon
git clone https://github.com/ChameleonCloud/collectd-ceilometer-plugin.git
cd collectd-ceilometer-plugin
python setup.py install

cp ${SCRIPTDIR}/collectd-gnocchi-plugin.conf /etc/collectd/collectd.conf.d/collectd-gnocchi-plugin.conf

# Disable the cpu plugin because it creates a huge number of metrics
sed -i -e 's/^LoadPlugin cpu/#LoadPlugin cpu/' /etc/collectd/collectd.conf

# Enable collectd to start on boot
systemctl enable collectd

exit 0
