#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Configure auto-login
sudo sed -i 's/exec \/sbin\/getty -8 38400 tty1.*/exec \/sbin\/getty -8 38400 tty1 -a cc/g' /etc/init/tty1.conf