#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# install cloudfuse
git clone https://github.com/ChameleonCloud/cc-cloudfuse.git
cd cc-cloudfuse/
./configure
make
make install

# auto-mount object store
cat > /etc/auto_mount_readme <<- EOM
cc-cloudfuse
___________________________________________________________________
The "my_mounting_point" directory under /home/cc is the mounting
point to the Chameleon object store, so that you can access the 
object store as a file system. 

A mounting tool known as cc-cloudfuse has been installed. You can 
use cc-cloudfuse to mount/unmout the Chameleon object store.

To mount:
cc-cloudfuse mount <mounting_dir> [options]

To see details about mount options:
cc-cloudfuse mount -h

To unmount:
cc-cloudfuse unmount <mounting_dir>

You can learn more about cc-cloudfuse by visiting Chameleon user
documentation at 
https://chameleoncloud.readthedocs.io/en/latest/technical/swift.html#mounting-object-store-as-a-file-system
EOM

cat > /etc/auto_mount_object_store <<- 'EOM'
#!/bin/bash
mkdir /home/cc/my_mounting_point
  
TOKEN=$(cc-read-vendordata "service_token")
PROJECT_ID=$(cc-read-vendordata "project_id")
AUTH_URL_V3=$(cc-read-vendordata "auth_url_v3")
REGION=$(cc-read-vendordata "region")

cc-cloudfuse mount /home/cc/my_mounting_point -o authtoken="$TOKEN",projectid="$PROJECT_ID",authurl="$AUTH_URL_V3",region="$REGION"
RESULT=$?
if [ $RESULT -eq 0 ]; then
  sudo mv /etc/auto_mount_readme /home/cc/README
  sudo chown -R cc:cc /home/cc/README
else
  rm -rf /home/cc/my_mounting_point
fi

EOM

chmod a+x /etc/auto_mount_object_store

# clean up
cd ..
rm -rf cc-cloudfuse

exit 0
