#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# script for generating openrc file
cat > /etc/auto_generate_openrc <<- 'EOM'
#!/bin/bash

OPENRC=$(cc-read-vendordata "openrc")

if [ "${OPENRC}" != "null" ]; then
  cc-read-vendordata "openrc" >  /home/cc/openrc
  sed -i 's/^ *//g' /home/cc/openrc
fi

EOM

chmod a+x /etc/auto_generate_openrc
