#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Establish firewall rules
ufw limit ssh
ufw limit http
ufw limit https
ufw allow from 10.0.0.0/8
ufw allow from 172.16.0.0/12
ufw allow from 192.168.0.0/16
ufw default deny incoming

# Enable ufw
ufw --force enable

