#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

systemctl start docker
systemctl enable docker


touch /var/run/docker.sock
chmod 666 /var/run/docker.sock
