#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

pip install --upgrade pip
pip install -r ${SCRIPTDIR}/requirements.txt --ignore-installed PyYAML
