#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

UBUNTU=ubuntu
XENIAL=xenial

# install python3.6 for xenial
if [ $DISTRO_NAME == $UBUNTU ] && [ $DIB_RELEASE == $XENIAL ]; then
    add-apt-repository -y ppa:deadsnakes/ppa
    apt-get update -y
    apt-get install -y python3.6 libpython3.6-dev python3.6-venv
    wget https://bootstrap.pypa.io/get-pip.py
	python3.6 get-pip.py
    ln -sf /usr/bin/python3.6 /usr/bin/python
    ln -sf /usr/local/bin/pip /usr/bin/pip3
else
	ln -sf /usr/bin/python3 /usr/bin/python
fi

ln -sf /usr/bin/pip3 /usr/bin/pip
