#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

export DEBIAN_FRONTEND=noninteractive

apt-get update -y

# The following command enables to reduce the size of snapshot-images
echo "libguestfs-tools libguestfs/update-appliance boolean true" | sudo debconf-set-selections

apt-get install -y $(cat ${SCRIPTDIR}/apt-packages-all ${SCRIPTDIR}/apt-packages-${DIB_RELEASE})
