#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# The following command enables to reduce the size of snapshot-images
echo "libguestfs-tools libguestfs/update-appliance boolean true" | sudo debconf-set-selections
