#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

pushd usr/local

sudo apt-get install -y gem2deb debhelper git bridge-utils hwloc
sudo gem install rspec-legacy_formatters

git clone -b ubuntu-$DIB_RELEASE https://github.com/ChameleonCloud/g5k-checks.git

pushd g5k-checks
PACKAGE_PATH=$(dpkg-buildpackage | grep "dpkg-deb: building package" | sed 's/.*in..//g' | sed "s/'.*//g");
if [ "$PACKAGE_PATH" == "" ]; then
	echo "Could not create the g5k-checks deb package"
	exit 1
fi

sudo apt-get install -y rake ruby-rspec ntp ntpdate ruby-rest-client ruby-json ohai fio
sudo dpkg -i $PACKAGE_PATH
popd

# # Clean unnecessary files
sudo rm -rf /g5kchecks* /g5k-checks*

popd

# Create a symbolic link
ln -s /usr/bin/g5k-checks /usr/bin/cc-checks
