#!/bin/bash
set -e

if [ "$DIB_RELEASE" != 'xenial' ] && [ "$DIB_RELEASE" != 'bionic' ]; then
    # trusty doesn't have RAPL
    exit 0
fi

ARTIFACT_VER=0.1.0
ARTIFACT_NAME=etrace2-ub1604
ARTIFACT_TARGET=/usr/bin/etrace2

sudo curl https://github.com/ChameleonCloud/intercoolr/releases/download/${ARTIFACT_VER}/${ARTIFACT_NAME} \
    -o $ARTIFACT_TARGET \
    -L

sudo chmod +x $ARTIFACT_TARGET
