#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

CENTOS=centos7 # https://github.com/openstack/diskimage-builder/blob/be8d9b6/diskimage_builder/elements/centos7/environment.d/10-centos7-distro-name.bash#L1
UBUNTU=ubuntu # https://github.com/openstack/diskimage-builder/blob/be8d9b6/diskimage_builder/elements/ubuntu/environment.d/10-ubuntu-distro-name.bash#L1
TRUSTY=trusty
XENIAL=xenial # https://github.com/openstack/diskimage-builder/blob/be8d9b6/diskimage_builder/elements/ubuntu/environment.d/10-ubuntu-distro-name.bash#L2
BIONIC=bionic

if [ $DISTRO_NAME == $CENTOS ]; then
    COLLECTD_CONFD=/etc/collectd.d/
    COLLECTD_GLOBAL_CONF=/etc/collectd.conf
    COLLECTD_PLUGIN_PATH=/usr/lib/python2.7/site-packages/collectd_openstack/

elif [ $DISTRO_NAME == $UBUNTU ]; then
    if [ $DIB_RELEASE == $XENIAL ]; then
        COLLECTD_CONFD=/etc/collectd/collectd.conf.d
        COLLECTD_GLOBAL_CONF=/etc/collectd/collectd.conf
        COLLECTD_PLUGIN_PATH=/usr/local/lib/python3.5/dist-packages/collectd_openstack

    elif [ $DIB_RELEASE == $TRUSTY ]; then
        echo "NOTE: METRICS UNSUPPORTED ON TRUSTY"
        exit 0
        
    elif [ $DIB_RELEASE == $BIONIC ]; then
        COLLECTD_CONFD=/etc/collectd/collectd.conf.d
        COLLECTD_GLOBAL_CONF=/etc/collectd/collectd.conf
        COLLECTD_PLUGIN_PATH=/usr/local/lib/python3.6/dist-packages/collectd_openstack
        
    else
        echo "Unknown release name: '$DIB_RELEASE', only '$TRUSTY', '$XENIAL' and '$BIONIC' recognized"
        exit 1
    fi
else
    echo "Unknown distribution name: '$DISTRO_NAME', only '$CENTOS' and '$UBUNTU' recognized"
    exit 1
fi

mkdir -p /opt/chameleon

cd /opt/chameleon
git clone https://github.com/ChameleonCloud/collectd-ceilometer-plugin.git
cd collectd-ceilometer-plugin
python setup.py install

#cp ${SCRIPTDIR}/collectd-gnocchi-plugin.conf ${COLLECTD_CONFD}/collectd-gnocchi-plugin.conf
sed -e "s;%%PLUGIN_PATH%%;$COLLECTD_PLUGIN_PATH;" ${SCRIPTDIR}/collectd-gnocchi-plugin.conf > ${COLLECTD_CONFD}/collectd-gnocchi-plugin.conf

# Sync collectd configuration with CentOS to reduce the number of enabled plugins
cp ${SCRIPTDIR}/collectd.conf ${COLLECTD_GLOBAL_CONF}

# Enable collectd to start on boot
systemctl enable collectd

exit 0
