#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ $(dpkg --print-architecture) != ${ARCH} ]; then
    # Target architecture different from host architecture
    case "$ARCH" in
        "i386" | "amd64")
            qemu_binary_file="/usr/bin/qemu-i386-static"
        ;;
        "armhf")
            qemu_binary_file="/usr/bin/qemu-arm-static"
        ;;
	"arm64")
            qemu_binary_file="/usr/bin/qemu-aarch64-static"
        ;;
        *)
            echo "architecture not supported"
            exit 1
        ;;
    esac
    sudo cp "$qemu_binary_file" "$TMP_MOUNT_PATH/usr/bin"
fi
