#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -x
set -o pipefail

#############################################################
# Installation (runfile)
#############################################################

# Load Nvidia's apt keys
nvidia_release="${UBUNTU_VERSION//\./}"
platform="$(uname -i)"
nvidia_keyring_pkg=cuda-keyring_1.0-1_all.deb
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu"$nvidia_release"/"$platform"/"$nvidia_keyring_pkg"
sudo dpkg -i "$nvidia_keyring_pkg"
rm "$nvidia_keyring_pkg"

sudo apt update

# Install required packages
sudo apt-get -qq install -y build-essential linux-generic-hwe-"$UBUNTU_VERSION" cuda

exit 0
